# Generated by Django 2.2.1 on 2019-06-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('username', models.CharField(max_length=12, unique=True)),
                ('email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=32)),
                ('vendor', models.CharField(max_length=32)),
                ('mrp', models.FloatField()),
                ('batch_num', models.CharField(max_length=32)),
                ('batch_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING')], max_length=8)),
            ],
        ),
    ]
